version: "3.7"

services:
  jbedwars:
    image: "jbedwars:latest"
    container_name: "JBedwars"
    restart: 'unless-stopped'
    ports:
      - '25565:25565/tcp'
    volumes:
      - '/home/jonas/Dokumente/Server/JBedwars/world:/opt/server/world'
      - '/home/jonas/Dokumente/Server/JBedwars/world_nether:/opt/server/world_nether'
      - '/home/jonas/Dokumente/Server/JBedwars/world_the_end:/opt/server/world_the_end'
    command: 'java -server -Xms3G -Xmx3G -jar paper.jar --nogui'
